(defvar emacs-dir   "~/.emacs.d/")
(defvar package-dir (concat emacs-dir "pkg/"))
(defvar temp-dir    (concat emacs-dir "tmp/"))
(defvar init-dir    (concat emacs-dir "init/"))
(defvar theme-dir   (concat emacs-dir "theme/"))

(load (concat emacs-dir "settings.el"))
(load (concat emacs-dir "functions.el"))
(load (concat emacs-dir "keys.el"))
(load (concat emacs-dir "custom.el"))
