# Unbind default tmux escape key
unbind-key C-a

# Bind backtick as escape key
set-option -g prefix `

# Ensure `` sends a single backtick
bind-key ` send-prefix

# Reload config
bind r source-file ~/.tmux.conf

# TERM variable
set-option -g default-terminal "screen-256color"

# Count windows from 1, 0 is too far away
set -g base-index 1

# Window titles
set-option -g set-titles on
set-option -g set-titles-string "#H:#S.#I.#P #W #T" # window number,program name,active (or not)
set-option -g status-utf8 on
set-option -g status-bg default
set-option -g status-fg white
set-option -g status-justify centre
set-option -g status-attr dim

# Default window title
set-window-option -g window-status-fg white
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# Active window title
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright

# Messages
set-option -g message-fg white
set-option -g message-bg black
set-option -g message-attr bright

# Left status user/host
set-option -g status-left-length 60
set-option -g status-left "#[fg=red]#(whoami)@#H:#S #[default]"
set-option -g status-right "#[fg=blue]%Y-%m-%d #[fg=white]%H:%M#[default]"
