#
# Escape Prefix
#

# Unbind default tmux escape key
unbind C-a

# Bind backtick as escape key
unbind `
set-option -g prefix `

# Ensure `` sends a single backtick
bind ` send-prefix

#
# Appearance
#

# TERM variable
set-option -g default-terminal "screen-256color"

# Window title = current command
setw -g automatic-rename on

# Inactive pane border
set-option -g pane-border-fg black
set-option -g pane-border-bg default

# Active pane border
set-option -g pane-active-border-fg black
set-option -g pane-active-border-bg default

# Window titles
set-option -g set-titles on
set-option -g set-titles-string "#H:#S.#I.#P #W #T" # window number,program name,active (or not)
set-option -g status-utf8 on
set-option -g status-bg default
set-option -g status-fg white
set-option -g status-justify centre
set-option -g status-attr dim

# Default window title
set-window-option -g window-status-fg black
set-window-option -g window-status-bg default
set-window-option -g window-status-attr default

# Active window title
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright

# Messages
set-option -g message-fg white
set-option -g message-bg black
set-option -g message-attr bright

# Left status user/host
set-option -g status-left-length 60
set-option -g status-left "#[fg=red]#(whoami)@#H:#S #[default]"
set-option -g status-right "#[fg=blue]%Y-%m-%d #[fg=white]%H:%M#[default]"

# Tab notifications
setw -g monitor-activity off

# Turn off status bar bell/notification
set -g visual-activity off

#
# Pane Manipulation
#

# Splitting
unbind %
bind = split-window -h
bind - split-window -v
bind \ break-pane

# Resizing
bind Down resize-pane -D 25
bind Up resize-pane -U 25
bind Left resize-pane -L 25
bind Right resize-pane -R 25

# Switch back (and forward) to last active window
bind a last-window

# Count windows from 1, 0 is too far away
set -g base-index 1

#
# Url View
#

# From currently active pane
bind u capture-pane \; save-buffer /tmp/tmux-url-buffer \; new-window -n "urlview" '$SHELL -c "urlview < /tmp/tmux-url-buffer"'

#
# Copy Mode
#

set-option -g default-command "reattach-to-user-namespace -l bash"

unbind -t emacs-copy M-w

bind -t emacs-copy c copy-selection
bind M-w send-keys c \; save-buffer /tmp/tmux-copy-buffer\; run-shell "reattach-to-user-namespace -l $SHELL -c 'cat /tmp/tmux-copy-buffer | pbcopy'"

#
# Reload
#

unbind r

bind r source-file ~/.tmux.conf

#
# History
#

set -g history-limit 250000

#
# Initial Windows
#

# neww -n emacs "emacs ~/Code"
