set -g base-index 1

bind-key f7 set-option -g prefix C-a
bind-key f8 set-option -g prefix `

set-option -g prefix `
bind r source-file ~/.tmux.conf

set -g status-justify centre

set-option -g default-terminal "screen-256color"

set-option -g set-titles on
set-option -g set-titles-string "#H:#S.#I.#P #W #T" # window number,program name,active (or not)
set-option -g status-utf8 on
set-option -g status-bg black
set-option -g status-fg white

# default statusbar colors
set -g status-fg white
set -g status-bg default
set -g status-attr bright

# default window title colors
set-window-option -g window-status-fg white
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright

# command/message line colors
set -g message-fg white
set -g message-bg black
set -g message-attr bright

set -g status-left-length 60
set -g status-left "#(whoami)#[fg=green]@#[fg=red]#H:#[fg=green]#S #[default]"
set -g status-right "#[fg=blue]%Y-%m-%d #[fg=white]%H:%M#[default]"
