#!/usr/bin/env bash

for path in ~/dotfiles/.[^.]*
do
  file=$(basename $path)
  case "$file" in
    .git* ) continue;;
  esac

  target=~/dotfiles/$file
  echo "[link] $file -> $target"
  ln -sf $target ~/$file
done

