#!/usr/bin/env bash

base=~/Dropbox/Code/dotfiles

for path in $base/.[^.]*
do
  file=$(basename $path)
  case "$file" in
    .git* ) continue;;
  esac

  target=$base/$file
  echo "[link] $target -> $file"
  ln -sf $target ~/$file
done

source ~/.bashrc
