#!/usr/bin/env bash

base=`pwd`

for path in .[^.]*
do
  file=$(basename $path)
  case "$file" in
    .git* ) continue;;
  esac

  echo "[link] $file -> ~/$file"
  ln -sf $base/$file ~/$file
done

source ~/.bashrc
