#
# Escape Prefix
#

# Unbind default tmux escape key
unbind C-a

# Bind backtick as escape key
unbind `
set-option -g prefix `

# Ensure `` sends a single backtick
bind ` send-prefix

#
# Appearance
#

# TERM variable
set-option -g default-terminal "screen-256color"

# set status bar
set-option -g status-utf8 on
set-option -g status-bg colour237
set-option -g status-fg colour241
set-option -g status-justify left

set-option -g status-left '##[bold]❐ #S#[default] ⡇'
set-option -g status-right '◔ #[bold]#[fg=colour242]%H:%M %p#[default] ⡇ %d.%m.%Y ⡇ ⌂ #(whoami)@#[bold]#[fg=colour242]#H#[default] '

set-option -g status-right-length 80
set-option -g status-left-length 20

# highlight active window
set-option -g window-status-current-bg colour237
set-option -g window-status-current-fg colour1
set-option -g window-status-current-attr bold
set-option -g window-status-current-format ' #I #W '

# set window notifications
set-option -g visual-activity off
set-option -g visual-content on
set-option -g monitor-activity off
set-option -g automatic-rename off

# tmux window titling for X
set-option -g set-titles on
set-option -g set-titles-string '[#I] #W'
set-option -g automatic-rename on
set-option -g window-status-format ' #I #W '
set-option -g window-status-attr dim

# starts windows at 1 not 0
set-option -g base-index 1

# start panes at 1 not 0
set-option -g pane-base-index 1

# enable mouse
set-option -g mouse-select-pane on
set-option -g mode-keys emacs
set-option -g mode-mouse on

# pane border
set-option -g pane-border-fg colour238
set-option -g pane-border-bg colour237
set-option -g pane-active-border-fg colour236
set-option -g pane-active-border-bg colour237

#
# Pane Manipulation
#

# Splitting
unbind %
bind = split-window -h
bind - split-window -v
bind \ break-pane

# Movement
bind-key j command-prompt -p "Join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "Send pane to:"  "join-pane -t '%%'"

# Resizing minor increment
bind Down resize-pane -D 5
bind Up resize-pane -U 5
bind Left resize-pane -L 5
bind Right resize-pane -R 5

# Resizing major increment
bind S-Down resize-pane -D 30
bind S-Up resize-pane -U 30
bind S-Left resize-pane -L 30
bind S-Right resize-pane -R 30

# Switch back (and forward) to last active window
bind a last-window

# Switch between panes
unbind f
bind f last-pane

# Count windows from 1, 0 is too far away
set -g base-index 1

#
# Url View
#

# From currently active pane
bind u capture-pane \; save-buffer /tmp/tmux-url-buffer \; new-window -n "urlview" '$SHELL -c "urlview < /tmp/tmux-url-buffer"'

#
# Copy Mode
#

set-option -g default-command "reattach-to-user-namespace -l bash"

unbind -t emacs-copy M-w

bind -t emacs-copy c copy-selection
bind M-w send-keys c \; save-buffer /tmp/tmux-copy-buffer\; run-shell "reattach-to-user-namespace -l $SHELL -c 'cat /tmp/tmux-copy-buffer | pbcopy'"

#
# Reload
#

unbind r

bind r source-file ~/.tmux.conf

#
# History
#

set -g history-limit 250000

