yl-go-to-char
backward-to-char

zap-to-char
zap-backward-to-char

(defvar ergo-minor-mode-map (make-sparse-keymap)
  "ergo-minor-mode keymap.")

(define-minor-mode ergo-minor-mode
  "A minor mode so that my key settings override annoying major modes."
  nil
  :lighter nil
  :global t
  :keymap ergo-minor-mode-map)

(defconst ergo-bindings
  '(("M-1" 'revert-buffer)
    ("C-3" 'read-notes)
    ("C-4" 'capture-notes)
    ("C-9" 'delete-other-windows)
    ("C-0" 'delete-window)
    ("C--" 'balance-windows)
    ("C-=" 'split-horizontal)
    ("C-\\" 'split-vertical)
    ("TAB" 'indent-or-indent-region)
    ("M-TAB" 'complete-symbol)
    ("M-q" 'zap-to-char)
    ("M-SPC-q" 'zap-backwards-to-char)
    ("M-w" 'start-of-line)
    ("M-SPC-w" 'kill-line-backwards)
    ("M-e" 'backward-paragraph)
    ("M-SPC-e" 'backward-page)
    ("M-r" 'end-of-line)
    ("M-SPC-r" 'kill-line)
    ("M-t" 'ido-find-file)
    ("M-SPC-t" 'find-file-in-project)
    ("C-y" 'list-current-directory)
    ("C-SPC-y" 'list-specific-directory)
    ("C-u" 'backward-symbol)
    ("C-SPC-u" 'previous-buffer)
    ("C-i" 'previous-line)
    ("C-SPC-i" 'beginning-of-buffer)
    ("C-o" 'forward-symbol)
    ("C-SPC-o" 'next-buffer)
    ("C-p" 'other-window)
    ("C-[" 'comment-or-comment-region)
    ("C-SPC-[" 'uncomment-or-uncomment-region)
    ("C-]" 'replace-string)
    ("C-SPC-]" 'replace-regexp)
    ("M-a" 'back-to-indentation)
    ("M-s" 'backward-word)
    ("M-SPC-s" 'backward-kill-word)
    ("M-d" 'forward-paragraph)
    ("M-SPC-d" 'forward-page)
    ("M-f" 'forward-word)
    ("M-SPC-f" 'forward-kill-word)
    ("M-g" 'execute-extended-command)
    ("M-SPC-g" 'shell-cmd-output-at-point)
    ("C-h" 'goto-line)
    ("C-SPC-h" 'recenter)
    ("C-j" 'backward-char)
    ("C-SPC-j" 'kill-char-back)
    ("C-k" 'next-line)
    ("C-SPC-k" 'end-of-buffer)
    ("C-l" 'forward-char)
    ("C-SPC-l" 'kill-char-forward)
    ("C-;" 'isearch-forward)
    ("C-SPC-;" 'isearch-reverse)
    ("C-'" 'occur)
    ("C-SPC-'" 'rgrep)
    ("M-z" 'undo)
    ("M-SPC-z" 'redo)
    ("M-SPC-x" 'kill-region)
    ("M-SPC-c" 'kill-ring-save)
    ("M-v" 'yank)
    ("M-SPC-v" 'yank-pop)
    ("M-b" 'ido-switch-buffer)
    ("M-SPC-b" 'kill-buffer)
    ("C-n" 'extend-selection)
    ("C-SPC-n" 'select-text-in-quote)
    ("C-m" 'transpose-words)
    ("C-SPC-m" 'transpose-sexps)
    ("C-," 'bookmark-jump)
    ("C-SPC-," 'bookmark-set)
    ("C-." 'fill-paragraph)
    ("C-/" 'align-regexp)))

(mapcar (lambda (binding)
          (let ((key (car binding))
                (cmd (cdr binding)))
            (define-key ergo-minor-mode-map key nil)
            (define-key ergo-minor-mode-map key cmd)
            key))
          ergo-bindings)

(defun my-minibuffer-setup-hook ()
  (ergo-minor-mode 0))

(provide 'ergo-minor-mode)
(ergo-minor-mode)
