(deftheme molokai)

(custom-theme-set-faces
 'molokai
 '(cursor ((t (:background "#ffffff"))))
 '(font-lock-builtin-face ((t (:foreground "#ae81ff"))))
 '(font-lock-function-name-face ((t (:foreground "#66d9ef"))))
 '(font-lock-type-face ((t (:foreground "#56f23f" :weight bold))))
 '(error ((t (:background "#1e0010" :foreground "#960050"))))
 '(font-lock-warning-face ((t (:inherit error))))
 '(font-lock-keyword-face ((t (:foreground "#f92672" :weight bold))))
 '(font-lock-delimiter-face ((t (:foreground "#8f8f8f"))))
 '(font-lock-constant-face ((t (:foreground "#fd971f"))))
 '(font-lock-string-face ((t (:foreground "#e6bb74"))))
 '(font-lock-comment-face ((t (:foreground "#687679" :italic nil))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(show-paren-match ((t (:background "#fd971f" :foreground "#000000"))))
 '(esk-paren-face ((t (:foreground "grey50"))))
 '(whitespace-tab ((t (:background "#272822"))))
 '(mode-line ((t (:background "#444444" :foreground "#86826e" :box t))))
 '(mode-line-inactive ((t (:inherit (mode-line) :background "#222222" :foreground "#293739" :box nil))))
 '(highlight ((t (:background "#403d3d" :inverse-video t))))
 '(region ((t (:inherit highlight :background "#49483e" :inverse-video nil))))
 '(hl-line ((t (:background "#293739" :inverse-video nil))))
 '(linum ((t (:foreground "#314849" :background "#111111"))))
 '(fringe ((t (:background "#161616"))))
 '(whitespace-trailing ((t (:background "#444444"))))
 '(font-lock-number-face ((t (:foreground "#ae81ff"))))
 '(font-lock-variable-name-face ((t (:foreground "#fd971f" :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#56f23f"))))
 '(linum-relative-current-face ((t (:inherit linum :foreground "#425949" :weight bold))))
 '(default ((t (:background "#161616" :foreground "#dddddd"))))
 '(vertical-border ((t (:background "black" :foreground "black")))))

(provide-theme 'molokai)
